import "./globals.css";

import { ptBR } from "@clerk/localizations";
import { auth, ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";

import { Navbar } from "./_components";

const inter = Inter({ subsets: ["latin"] });
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-Br">
        <body className={inter.className}>
          <Navbar />
          <div className="bg-slate-700 h-screen p-16">
            <TRPCReactProvider
              cookies={cookies().toString()}
              userId={userId as string}
            >
              {children}
            </TRPCReactProvider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
